Repository andela/zinnia-ah-backend, pull requests merged in 2019-05, with the labels that each got.

#69 #165575539 Fix existing username validation error
  src/routes/auth.route.js
  src/routes/controllers/users.controller.js
  src/routes/middlewares/duplicate-user.middleware.js
  src/routes/users.route.js
  src/tests/db/mockdata/userdata.js
  src/tests/db/models/users-validation.test.js
  src/tests/routes/controllers/users.test.js
  src/utils/helpers.utils.js
Labels: Ready for review

#71 #164797147 Ft Enable Google authentication
  .env.example
  .travis.yml
  package-lock.json
  package.json
  src/db/migrations/20190325172457-create-users.js
  src/db/models/User.js
  src/routes/auth.route.js
  src/routes/controllers/auth.controller.js
  src/routes/services/passport-strategies.services.js
  src/server.js
  src/tests/routes/controllers/social-auth.test.js
Labels: Ready for review, needs approval

#74 166027736-bug(password): modify url link to be in query
  src/routes/controllers/password.controller.js
  src/server.js
Labels: Ready for review

#56 #164797155 Create Notifications feature
  src/db/migrations/20190325172457-create-users.js
  src/db/migrations/20190413124019-create-notification.js
  src/db/models/Notification.js
  src/db/models/User.js
  src/db/seeders/20190416064848-seed-user-follower.js
  src/routes/controllers/articles.controller.js
  src/routes/controllers/auth.controller.js
  src/routes/controllers/comments.controller.js
  src/routes/controllers/follow.controller.js
  src/routes/controllers/password.controller.js
  src/routes/middlewares/authorized-user.middleware.js
  src/tests/routes/controllers/articles.test.js
  src/tests/utils/notifications/article-notification.test.js
  src/utils/helpers.utils.js
  src/utils/mail-template/mail-template.utils.js
  src/utils/notifications/article-notification.utils.js
  src/utils/notifications/comment-notification.utils.js
  src/utils/notifications/follow-notification.utils.js
Labels: Ready for review

#73 166026425 Bug change response to redirect after social auth
  package-lock.json
  src/db/models/index.js
  src/routes/auth.route.js
  src/routes/controllers/auth.controller.js
  src/routes/middlewares/request-refer.js
  src/routes/services/passport-strategies.services.js
  src/server.js
  src/tests/routes/controllers/comment.test.js
  src/tests/routes/controllers/social-auth.test.js
  src/utils/validation-schema.utils.js
Labels: Feedback implemented, Ready for review, needs approval

#46 #164797149 users can update article
  package-lock.json
  src/db/seeders/20190405073145-seed-user.js
  src/db/seeders/20190405073146-article-seeder.js
  src/routes/articles.route.js
  src/routes/auth.route.js
  src/routes/controllers/articles.controller.js
  src/routes/follow.route.js
  src/routes/highlights.route.js
  src/routes/middlewares/authorized-user.middleware.js
  src/routes/middlewares/validate-input.middleware.js
  src/routes/roles.route.js
  src/routes/users.route.js
  src/tests/db/mockdata/articledata.js
  src/tests/db/mockdata/userdata.js
  src/tests/routes/controllers/articles.test.js
  src/tests/routes/controllers/comment.test.js
  src/utils/helpers.utils.js
  src/utils/validation-schema.utils.js
Labels: Feedback implemented, needs approval

#65 #165441913 Get all likes by a user (articles and comments)
  package-lock.json
  package.json
  src/routes/controllers/users.controller.js
  src/routes/users.route.js
  src/tests/routes/controllers/users.test.js
Labels: Feedback implemented, Ready for review, needs approval

#79 Fix reset password bug. Implement don't send password to the client
  src/routes/controllers/articles.controller.js
  src/routes/controllers/auth.controller.js
  src/routes/controllers/password.controller.js
  src/tests/routes/controllers/auth.test.js
  src/tests/routes/controllers/password.test.js
  src/tests/routes/controllers/users.test.js
  src/tests/utils/notifications/article-notification.test.js
  src/utils/helpers.utils.js
Labels: Feedback implemented, needs approval
