Repository andela/zinnia-ah-backend, pull requests merged in 2019-04, with the labels that each got.

#24 #164797149 users can create article
  package-lock.json
  package.json
  src/db/migrations/20190403111055-create-article.js
  src/db/models/Article.js
  src/db/models/User.js
  src/routes/articles.route.js
  src/routes/auth.route.js
  src/routes/controllers/articles.controller.js
  src/routes/controllers/password.controller.js
  src/routes/controllers/users.controller.js
  src/routes/index.js
  src/tests/db/controller/article.test.js
Labels: Ready for review

#25 #164955297 setup migrations for project
  .gitignore
  .hound.yml
  package-lock.json
  package.json
  src/db/migrations/2019025172457-create-users.js
  src/db/migrations/20190403111055-create-article.js
  src/db/migrations/20190403212306-create-article.js
  src/db/migrations/20190403212400-create-comment.js
  src/db/migrations/20190403212412-create-rating.js
  src/db/migrations/20190403212522-create-bookmark.js
  src/db/migrations/20190404030709-create-report.js
  src/db/migrations/20190404051235-create-user-follow.js
  src/db/migrations/20190405003517-create-comment-likes.js
  src/db/migrations/20190405011452-create-article-likes.js
  src/db/migrations/20190408114438-create-tags.js
  src/db/migrations/20190408114555-create-images.js
  src/db/migrations/20190408125824-create-article-tags.js
  src/db/migrations/20190408125837-create-article-images.js
  src/db/migrations/20190410153550-create-user-mutes.js
  src/db/migrations/20190410154207-create-user-muted-authors.js
  src/db/models/Article.js
  src/db/models/ArticleLike.js
  src/db/models/Bookmark.js
  src/db/models/Comment.js
  src/db/models/CommentLike.js
  src/db/models/Image.js
  src/db/models/Rating.js
  src/db/models/Report.js
  src/db/models/Tag.js
  src/db/models/User.js
  src/db/seeders/20190405073145-seed-user.js
  src/db/seeders/20190405073146-article-seeder.js
  src/tests/db/article.test.js
  src/tests/db/user.test.js
  src/tests/db/userdata.js
  src/tests/db/users.test.js
  src/tests/routes/controllers/password.test.js
Labels: Ready for review

#21 164892371-feature(signin): user should be able to sign in
  package-lock.json
  package.json
  src/config/mail-config.js
  src/db/migrations/20190403212306-create-article.js
  src/db/models/Article.js
  src/db/models/User.js
  src/db/seeders/20190403132533-demo-user.js
  src/db/seeders/20190405073145-seed-user.js
  src/db/seeders/20190405073146-article-seeder.js
  src/routes/auth.route.js
  src/routes/controllers/articles.controller.js
  src/routes/controllers/auth.controller.js
  src/routes/controllers/password.controller.js
  src/routes/controllers/users.controller.js
  src/routes/index.js
  src/routes/middlewares/authorized-user.middleware.js
  src/routes/middlewares/validate-user.middleware.js
  src/routes/password.route.js
  src/routes/services/passport-strategies.services.js
  src/tests/config/mail-config.test.js
  src/tests/db/article.test.js
  src/tests/db/mockdata/userdata.js
  src/tests/db/model/users.test.js
  src/tests/db/user.test.js
  src/tests/routes/controllers/articles.test.js
  src/tests/routes/controllers/auth.test.js
  src/tests/routes/controllers/password.test.js
  src/tests/utils/helpers.test.js
  src/utils/helpers.utils.js
  src/utils/validation-schema.utils.js
Labels: Ready for review

#29 #164797154 Follow and unfollow a user
  .gitignore
  src/config/mail-config.js
  src/db/migrations/20190404051235-create-user-follow.js
  src/db/models/User.js
  src/db/seeders/20190405073145-seed-user.js
  src/routes/controllers/auth.controller.js
  src/routes/controllers/follow.controller.js
  src/routes/controllers/password.controller.js
  src/routes/follow.route.js
  src/routes/index.js
  src/routes/middlewares/authorized-user.middleware.js
  src/tests/db/mockdata/userdata.js
  src/tests/db/models/users.test.js
  src/tests/routes/controllers/articles.test.js
  src/tests/routes/controllers/auth.test.js
  src/tests/routes/controllers/follow.test.js
  src/tests/routes/controllers/password.test.js
  src/tests/routes/controllers/user.test.js
  src/utils/helpers.utils.js
Labels: Feedback implemented, Ready for review

#28 #164797158 List users functionality
  package-lock.json
  package.json
  src/db/migrations/2019025172457-create-users.js
  src/routes/controllers/users.controller.js
  src/routes/index.js
  src/routes/users.route.js
  src/server.js
  src/tests/routes/controllers/auth.test.js
  src/tests/routes/controllers/follow.test.js
  src/tests/routes/controllers/users.test.js
Labels: Feedback implemented, Ready for review

#41 #164797149 Get articles by Id endpoint
  package-lock.json
  package.json
  src/db/models/Article.js
  src/db/models/User.js
  src/db/seeders/20190405073146-article-seeder.js
  src/routes/articles.route.js
  src/routes/auth.route.js
  src/routes/controllers/articles.controller.js
  src/routes/index.js
  src/routes/middlewares/validate-input.middleware.js
  src/routes/middlewares/validate-user.middleware.js
  src/server.js
  src/tests/routes/controllers/articles.test.js
  src/tests/routes/controllers/follow.test.js
  src/utils/validation-schema.utils.js
  src/utils/validator.utils.js
Labels: Ready for review

#37 164797151 User comment Feature
  .env.example
  .eslintrc
  package.json
  src/db/migrations/20190403212400-create-comment.js
  src/db/models/User.js
  src/db/seeders/20190405073146-article-seeder.js
  src/db/seeders/20190410232221-comment-seeder.js
  src/routes/articles.route.js
  src/routes/auth.route.js
  src/routes/controllers/articles.controller.js
  src/routes/controllers/auth.controller.js
  src/routes/controllers/comments.controller.js
  src/routes/controllers/password.controller.js
  src/server.js
  src/tests/db/model/users-validation.test.js
  src/tests/routes/controllers/articles.test.js
  src/tests/routes/controllers/comment.test.js
  src/tests/routes/controllers/password.test.js
  src/utils/helpers.utils.js
  src/utils/validation-schema.utils.js
Labels: Feedback implemented, Ready for review

#40 #165035326 Fix Coveralls
  .babelrc
  .travis.yml
  package-lock.json
  package.json
  src/db/models/User.js
  src/tests/routes/controllers/articles.test.js
Labels: Feedback implemented

#33 #164797148 Create User Profile feature
  .DS_Store
  package-lock.json
  src/.DS_Store
  src/db/.DS_Store
  src/db/migrations/.DS_Store
  src/db/migrations/20190325172457-create-users 23-20-20-756.js
  src/db/migrations/20190325172457-create-users.js
  src/routes/controllers/users.controller.js
  src/routes/index.js
  src/routes/users.route.js
  src/tests/routes/controllers/articles.test.js
  src/tests/routes/controllers/password.test.js
  src/tests/routes/controllers/user.test.js
  src/tests/routes/controllers/users.test.js
Labels: Feedback implemented

#42 #164797160 Users can see the time it takes to read an Article
  package-lock.json
  package.json
  src/routes/controllers/articles.controller.js
  src/tests/readtime.test.js
  src/utils/readtime.utils.js
Labels: Feedback implemented, Fix merge conflicts, needs approval

#31 [feat #164797149] users can delete articles there created
  package-lock.json
  src/routes/articles.route.js
  src/routes/controllers/articles.controller.js
  src/routes/controllers/password.controller.js
  src/routes/services/passport-strategies.services.js
  src/tests/db/mockdata/userdata.js
  src/tests/routes/controllers/articles.test.js
  src/utils/helpers.utils.js
Labels: Feedback implemented, needs approval

#48 164797164 Users can like a comment
  src/db/migrations/20190405003517-create-comment-likes.js
  src/db/models/Comment.js
  src/db/models/CommentLike.js
  src/db/seeders/20190405073145-seed-user.js
  src/routes/articles.route.js
  src/routes/controllers/comments.controller.js
  src/routes/index.js
  src/routes/middlewares/authorized-user.middleware.js
  src/tests/db/mockdata/userdata.js
  src/tests/routes/controllers/auth.test.js
  src/tests/routes/controllers/comment-like.test.js
Labels: Feedback implemented, needs approval

#47 #164797166 Sets up roles and access control
  package-lock.json
  src/db/migrations/2019025172457-create-users.js
  src/db/migrations/20190403212306-create-article.js
  src/db/migrations/20190410153550-create-user-muted-tags.js
  src/db/models/Article.js
  src/db/models/User.js
  src/db/seeders/20190405073145-seed-user.js
  src/routes/articles.route.js
  src/routes/controllers/articles.controller.js
  src/routes/controllers/auth.controller.js
  src/routes/controllers/roles.controller.js
  src/routes/index.js
  src/routes/middlewares/authorized-user.middleware.js
  src/routes/middlewares/verify-admin.middleware.js
  src/routes/roles.route.js
  src/tests/db/mockdata/userdata.js
  src/tests/routes/controllers/comment-like.test.js
  src/tests/routes/controllers/comment.test.js
  src/tests/routes/controllers/roles.test.js
  src/utils/constants.js
  src/utils/helpers.utils.js
Labels: Feedback implemented, needs approval

#51 #164797161 Share article via Email
  src/routes/articles.route.js
  src/routes/controllers/articles.controller.js
  src/tests/routes/controllers/articles.test.js
Labels: Feedback implemented, Ready for review

#54 #164797162 user can bookmark article
  .DS_Store
  package-lock.json
  src/db/migrations/.DS_Store
  src/db/migrations/2019025172457-create-users.js
  src/db/migrations/20190325172457-create-users 23-20-20-756.js
  src/db/migrations/20190325172457-create-users.js
  src/db/migrations/20190403212522-create-bookmark.js
  src/db/models/Bookmark.js
  src/db/models/User.js
  src/routes/articles.route.js
  src/routes/controllers/articles.controller.js
  src/tests/routes/controllers/articles.test.js
  src/tests/routes/controllers/comment-like.test.js
  src/utils/helpers.utils.js
Labels: Feedback implemented, needs approval

#52 [Feature 164797168] Added functionality that enables users edit their comments and track comment history
  src/db/migrations/20190415172646-create-comment-history.js
  src/db/models/CommentHistory.js
  src/routes/articles.route.js
  src/routes/controllers/comments.controller.js
  src/tests/routes/controllers/comment.test.js
Labels: Ready for review

#50 #164797167 Create highlight and comment
  package-lock.json
  package.json
  src/db/migrations/20190414160047-create-highlight.js
  src/db/models/Article.js
  src/db/models/Highlight.js
  src/db/models/User.js
  src/db/seeders/20190405073146-article-seeder.js
  src/db/seeders/20190417163830-highlight-seeder.js
  src/routes/controllers/highlights.controller.js
  src/routes/highlights.route.js
  src/routes/index.js
  src/tests/db/mockdata/userdata.js
  src/tests/routes/controllers/highlights.test.js
  src/utils/helpers.utils.js
Labels: Feedback implemented, needs approval

#57 #164797159 articles search functionality with custom filtering
  src/db/migrations/20190408125824-create-article-tags.js
  src/db/models/Article.js
  src/db/models/Tag.js
  src/db/seeders/20190405073145-seed-user.js
  src/db/seeders/20190405073146-article-seeder.js
  src/db/seeders/20190415171402-tags-seeder.js
  src/db/seeders/20190415171414-article-tags-seeder.js
  src/routes/controllers/search.controller.js
  src/routes/index.js
  src/routes/search.route.js
  src/server.js
  src/tests/db/models/users-validation.test.js
  src/tests/routes/controllers/search.test.js
Labels: Feedback implemented, needs approval

#58 #164797163 User can report an article
  src/.DS_Store
  src/db/migrations/20190404030709-create-report.js
  src/db/models/Report.js
  src/routes/articles.route.js
  src/routes/controllers/articles.controller.js
  src/tests/routes/controllers/articles.test.js
  src/utils/constants.js
Labels: Feedback implemented, Ready for review

#60 #165441872 Write test for helper functions and remove redundant helper functions
  src/db/models/User.js
  src/db/seeders/20190405073146-article-seeder.js
  src/routes/middlewares/index.js
  src/server.js
  src/tests/config/mail-config.test.js
  src/tests/readtime.test.js
  src/tests/routes/controllers/articles.test.js
  src/tests/routes/controllers/highlights.test.js
  src/tests/server.test.js
  src/tests/utils/helpers.test.js
  src/utils/helpers.utils.js
Labels: Ready for review

#59 #164797165 capture and show user reading stats
  src/db/migrations/20190403212306-create-article.js
  src/db/migrations/20190417075437-create-reading-stats.js
  src/db/models/ReadingStats.js
  src/db/models/User.js
  src/db/seeders/20190405073146-article-seeder.js
  src/routes/articles.route.js
  src/routes/controllers/articles.controller.js
  src/routes/controllers/users.controller.js
  src/routes/users.route.js
  src/server.js
  src/tests/db/mockdata/articledata.js
  src/tests/db/mockdata/userdata.js
  src/tests/routes/controllers/articles.test.js
  src/tests/routes/controllers/users.test.js
Labels: Feedback implemented, needs approval

#61 #165441913 Attach user's articles and following stats to user profile
  src/routes/controllers/users.controller.js
  src/tests/routes/controllers/users.test.js
Labels: Ready for review

#62 #165441913 Get all reports by a user
  src/routes/controllers/users.controller.js
  src/routes/users.route.js
  src/tests/routes/controllers/users.test.js
Labels: Feedback implemented, Ready for review

#63 [feature #165441913] Get all bookmarks by a user
  src/routes/controllers/users.controller.js
  src/routes/users.route.js
  src/tests/routes/controllers/users.test.js
Labels: Feedback implemented, Ready for review

#45 #164797157 create article pagination endpoint
  src/routes/articles.route.js
  src/routes/controllers/articles.controller.js
  src/routes/controllers/users.controller.js
  src/tests/routes/controllers/articles.test.js
  src/utils/helpers.utils.js
Labels: Feedback implemented, needs approval

#64 #165441913 Get all comments by a user
  src/db/models/Article.js
  src/db/models/Comment.js
  src/routes/controllers/articles.controller.js
  src/routes/controllers/users.controller.js
  src/routes/users.route.js
  src/tests/routes/controllers/users.test.js
Labels: Feedback implemented, Ready for review

#66 #165561063 Create helper for server error messages
  src/routes/controllers/articles.controller.js
  src/routes/controllers/auth.controller.js
  src/routes/controllers/comments.controller.js
  src/routes/controllers/follow.controller.js
  src/routes/controllers/highlights.controller.js
  src/routes/controllers/roles.controller.js
  src/routes/controllers/search.controller.js
  src/routes/controllers/users.controller.js
  src/utils/helpers.utils.js
Labels: Ready for review

#53 #164797150 users can rate article
  .DS_Store
  package-lock.json
  package.json
  src/db/.DS_Store
  src/db/migrations/.DS_Store
  src/db/models/Article.js
  src/db/models/Rating.js
  src/db/models/index.js
  src/db/seeders/20190405073145-seed-user.js
  src/db/seeders/20190405073146-article-seeder.js
  src/db/seeders/20190410232221-comment-seeder.js
  src/db/seeders/20190415171402-tags-seeder.js
  src/db/seeders/20190417163830-highlight-seeder.js
  src/routes/articles.route.js
  src/routes/controllers/articles.controller.js
  src/routes/middlewares/validate-input.middleware.js
  src/tests/db/mockdata/articledata.js
  src/tests/db/mockdata/urldata.js
  src/tests/routes/controllers/articles.test.js
  src/utils/validation-schema.utils.js
Labels: Feedback implemented, needs approval
